DROP TABLE IF EXISTS top_channel;
CREATE TABLE top_channel (
channel TEXT,
device_count TEXT
);

INSERT INTO top_channel VALUES ('BN HD', '29083');
INSERT INTO top_channel VALUES ('RTRS', '27414');
INSERT INTO top_channel VALUES ('ATV HD', '19238');
INSERT INTO top_channel VALUES ('Prva', '17974');
INSERT INTO top_channel VALUES ('SUPERSTAR HD', '17639');
INSERT INTO top_channel VALUES ('RTS 1', '16510');
INSERT INTO top_channel VALUES ('Pink BH', '14891');
INSERT INTO top_channel VALUES ('Informer TV HD', '12356');
INSERT INTO top_channel VALUES ('Kurir TV HD', '11324');
INSERT INTO top_channel VALUES ('FTV HD', '10201');
INSERT INTO top_channel VALUES ('Happy TV', '9957');
INSERT INTO top_channel VALUES ('Blic TV HD', '9918');
INSERT INTO top_channel VALUES ('Arena Premium 5 HD', '9658');
INSERT INTO top_channel VALUES ('Euronews Serbia HD', '9597');
INSERT INTO top_channel VALUES ('Tanjug TV', '9355');
INSERT INTO top_channel VALUES ('BHT 1 HD', '9218');
INSERT INTO top_channel VALUES ('TV K3 HD', '9113');
INSERT INTO top_channel VALUES ('AlfaTV', '8967');
INSERT INTO top_channel VALUES ('Nova BH HD', '8157');
INSERT INTO top_channel VALUES ('RTL HD', '7898');
INSERT INTO top_channel VALUES ('BN Music HD', '7830');
INSERT INTO top_channel VALUES ('Vesti', '6520');
INSERT INTO top_channel VALUES ('B92', '6480');
INSERT INTO top_channel VALUES ('UNA TV HD', '6473');
INSERT INTO top_channel VALUES ('HRT 1 HD', '6396');
INSERT INTO top_channel VALUES ('BN 2 HD', '6224');
INSERT INTO top_channel VALUES ('Red TV', '5920');
INSERT INTO top_channel VALUES ('Balkan Trip HD', '5867');
INSERT INTO top_channel VALUES ('K1', '5263');
INSERT INTO top_channel VALUES ('Euronews BiH HD', '5236');
INSERT INTO top_channel VALUES ('Arena Premium 1 HD', '4816');
INSERT INTO top_channel VALUES ('RTL 2 HD', '4740');
INSERT INTO top_channel VALUES ('Pink Action', '4718');
INSERT INTO top_channel VALUES ('Arena Sport 7 HD', '4594');
INSERT INTO top_channel VALUES ('Arena Premium 4 HD', '4422');
INSERT INTO top_channel VALUES ('HRT 2 HD', '4367');
INSERT INTO top_channel VALUES ('Erotic 8', '4213');
INSERT INTO top_channel VALUES ('RTS Drama', '4104');
INSERT INTO top_channel VALUES ('Arena Premium 2 HD', '4081');
INSERT INTO top_channel VALUES ('Arena Premium 3 HD', '3893');
INSERT INTO top_channel VALUES ('Erotic 7', '3837');
INSERT INTO top_channel VALUES ('RTS Svet', '3783');
INSERT INTO top_channel VALUES ('OBN HD', '3721');
INSERT INTO top_channel VALUES ('Klasik', '3700');
INSERT INTO top_channel VALUES ('Pink Thriller', '3630');
INSERT INTO top_channel VALUES ('Pink Premium', '3599');
INSERT INTO top_channel VALUES ('RTS Život', '3554');
INSERT INTO top_channel VALUES ('Erotic 4', '3417');
INSERT INTO top_channel VALUES ('Narodna TV HD', '3359');
INSERT INTO top_channel VALUES ('Pink Western', '3320');
INSERT INTO top_channel VALUES ('RTS 2', '3315');
INSERT INTO top_channel VALUES ('Erotic 5', '3240');
INSERT INTO top_channel VALUES ('Pink Film', '3226');
INSERT INTO top_channel VALUES ('Star Movies HD', '3211');
INSERT INTO top_channel VALUES ('Arena Sport 7', '3184');
INSERT INTO top_channel VALUES ('Izvorna TV', '3179');
INSERT INTO top_channel VALUES ('Pink Romance', '3173');
INSERT INTO top_channel VALUES ('SUPERSTAR 3 HD', '3155');
INSERT INTO top_channel VALUES ('Arena Sport 2', '3154');
INSERT INTO top_channel VALUES ('Pink Crime & Mystery', '3141');
INSERT INTO top_channel VALUES ('Ras TV', '3116');
INSERT INTO top_channel VALUES ('Hayat TV', '3069');
INSERT INTO top_channel VALUES ('Erotic 6', '3062');
INSERT INTO top_channel VALUES ('Pink Comedy', '3051');
INSERT INTO top_channel VALUES ('Arena Premium 1', '3023');
INSERT INTO top_channel VALUES ('Nick Jr.', '2963');
INSERT INTO top_channel VALUES ('Viasat Kino', '2931');
INSERT INTO top_channel VALUES ('Erotic 3', '2924');
INSERT INTO top_channel VALUES ('Nickelodeon', '2891');
INSERT INTO top_channel VALUES ('Arena Premium 5', '2853');
INSERT INTO top_channel VALUES ('Pink', '2852');
INSERT INTO top_channel VALUES ('INFO', '2747');
INSERT INTO top_channel VALUES ('RTRS Plus', '2728');
INSERT INTO top_channel VALUES ('AMC', '2679');
INSERT INTO top_channel VALUES ('Star Channel HD', '2664');
INSERT INTO top_channel VALUES ('Arena Sport 2 HD', '2647');
INSERT INTO top_channel VALUES ('Pink World Cinema', '2644');
INSERT INTO top_channel VALUES ('Pink Movies', '2617');
INSERT INTO top_channel VALUES ('Pink Sci-Fi & Fantasy', '2589');
INSERT INTO top_channel VALUES ('Erotic', '2563');
INSERT INTO top_channel VALUES ('Erotic 2', '2505');
INSERT INTO top_channel VALUES ('Hype TV', '2481');
INSERT INTO top_channel VALUES ('RTV 1', '2462');
INSERT INTO top_channel VALUES ('Arena Sport 1', '2393');
INSERT INTO top_channel VALUES ('Bloomberg Adria HD', '2381');
INSERT INTO top_channel VALUES ('TVSA HD', '2342');
INSERT INTO top_channel VALUES ('RTS 3', '2289');
INSERT INTO top_channel VALUES ('Arena Premium 2', '2273');
INSERT INTO top_channel VALUES ('Newsmax Balkans HD', '2268');
INSERT INTO top_channel VALUES ('Pink Classic', '2241');
INSERT INTO top_channel VALUES ('BHT 1', '2151');
INSERT INTO top_channel VALUES ('NickToons', '2136');
INSERT INTO top_channel VALUES ('Prva Max', '2115');
INSERT INTO top_channel VALUES ('SUPERSTAR 2', '2069');
INSERT INTO top_channel VALUES ('HRT 3 HD', '2056');
INSERT INTO top_channel VALUES ('FilmBox Stars', '2017');
INSERT INTO top_channel VALUES ('History', '1972');
INSERT INTO top_channel VALUES ('Arena Premium 3', '1956');
INSERT INTO top_channel VALUES ('National Geographic', '1796');
INSERT INTO top_channel VALUES ('Arena Sport 1 HD', '1741');
INSERT INTO top_channel VALUES ('Diva', '1721');
INSERT INTO top_channel VALUES ('Star Life', '1699');
INSERT INTO top_channel VALUES ('Dankos plus televizija ', '1693');
INSERT INTO top_channel VALUES ('Arena Sport 3', '1669');
INSERT INTO top_channel VALUES ('Arena Premium 4', '1659');
INSERT INTO top_channel VALUES ('Discovery Channel', '1613');
INSERT INTO top_channel VALUES ('Eroxxx', '1595');
INSERT INTO top_channel VALUES ('Ekovizija HD', '1584');
INSERT INTO top_channel VALUES ('K::CN 1', '1567');
INSERT INTO top_channel VALUES ('Arena Sport 3 HD', '1564');
INSERT INTO top_channel VALUES ('RTV Vikom', '1549');
INSERT INTO top_channel VALUES ('Eurosport 1 HD', '1535');
INSERT INTO top_channel VALUES ('ITV Story HD', '1528');
INSERT INTO top_channel VALUES ('Adriatic Sport 1 HD', '1496');
INSERT INTO top_channel VALUES ('Balkan TV', '1467');
INSERT INTO top_channel VALUES ('Minimax', '1453');
INSERT INTO top_channel VALUES ('Face TV', '1452');
INSERT INTO top_channel VALUES ('Arena Fight HD', '1438');
INSERT INTO top_channel VALUES ('Viasat Nature', '1433');
INSERT INTO top_channel VALUES ('Eurosport 1', '1422');
INSERT INTO top_channel VALUES ('FilmBox Extra', '1417');
INSERT INTO top_channel VALUES ('Arena Sport 4', '1415');
INSERT INTO top_channel VALUES ('Arena Sport 6 HD', '1414');
INSERT INTO top_channel VALUES ('Toxic TV', '1409');
INSERT INTO top_channel VALUES ('Arena Sport 6', '1386');
INSERT INTO top_channel VALUES ('BHT HD', '1382');
INSERT INTO top_channel VALUES ('Arena Sport 4 HD', '1352');
INSERT INTO top_channel VALUES ('Televizija Hram', '1345');
INSERT INTO top_channel VALUES ('Euro Cinema 4', '1327');
INSERT INTO top_channel VALUES ('Hype 2', '1258');
INSERT INTO top_channel VALUES ('RTV 2', '1243');
INSERT INTO top_channel VALUES ('Zvezda TV HD', '1232');
INSERT INTO top_channel VALUES ('Erox', '1222');
INSERT INTO top_channel VALUES ('SciFi HD', '1195');
INSERT INTO top_channel VALUES ('Euro Cinema 2', '1178');
INSERT INTO top_channel VALUES ('Herceg televizija HD', '1166');
INSERT INTO top_channel VALUES ('Euro Cinema 1', '1154');
INSERT INTO top_channel VALUES ('Epic Drama', '1142');
INSERT INTO top_channel VALUES ('Eurosport 2 HD', '1131');
INSERT INTO top_channel VALUES ('FTV', '1130');
INSERT INTO top_channel VALUES ('Koreni', '1119');
INSERT INTO top_channel VALUES ('DOX TV', '1108');
INSERT INTO top_channel VALUES ('Arena Sport 1x2', '1106');
INSERT INTO top_channel VALUES ('Pink Family', '1093');
INSERT INTO top_channel VALUES ('TV Nikšić', '1089');
INSERT INTO top_channel VALUES ('Hayat 2', '1082');
INSERT INTO top_channel VALUES ('BBC Earth HD', '1075');
INSERT INTO top_channel VALUES ('AXN', '1066');
INSERT INTO top_channel VALUES ('O Kanal HD', '1056');
INSERT INTO top_channel VALUES ('RTS Trezor', '1044');
INSERT INTO top_channel VALUES ('Arena Tenis HD', '1041');
INSERT INTO top_channel VALUES ('Premier League TV HD', '1004');
INSERT INTO top_channel VALUES ('ID', '998');
INSERT INTO top_channel VALUES ('Arena Sport 5', '991');
INSERT INTO top_channel VALUES ('Viasat History', '990');
INSERT INTO top_channel VALUES ('RTVIS', '946');
INSERT INTO top_channel VALUES ('NTV Arena HD', '940');
INSERT INTO top_channel VALUES ('ITV Master HD', '936');
INSERT INTO top_channel VALUES ('Arena Sport 5 HD', '911');
INSERT INTO top_channel VALUES ('Euro Cinema 3', '909');
INSERT INTO top_channel VALUES ('TLC', '893');
INSERT INTO top_channel VALUES ('RTL kockica HD', '886');
INSERT INTO top_channel VALUES ('Arena Tenis', '866');
INSERT INTO top_channel VALUES ('RTS Nauka HD', '850');
INSERT INTO top_channel VALUES ('RTV Hit', '836');
INSERT INTO top_channel VALUES ('Pink Serije', '828');
INSERT INTO top_channel VALUES ('Cartoonito', '817');
INSERT INTO top_channel VALUES ('Super Sat TV', '814');
INSERT INTO top_channel VALUES ('Viasat Explore', '811');
INSERT INTO top_channel VALUES ('Eurosport 2', '806');
INSERT INTO top_channel VALUES ('Adria TV', '801');
INSERT INTO top_channel VALUES ('Pink Soap', '795');
INSERT INTO top_channel VALUES ('Star Crime HD', '792');
INSERT INTO top_channel VALUES ('Hayat HD', '791');
INSERT INTO top_channel VALUES ('Prijedor TV', '784');
INSERT INTO top_channel VALUES ('Toxic Folk', '779');
INSERT INTO top_channel VALUES ('RTV Gradiska HD', '766');
INSERT INTO top_channel VALUES ('Prva World', '762');
INSERT INTO top_channel VALUES ('Baby TV', '754');
INSERT INTO top_channel VALUES ('Timeless Dizi Channel', '733');
INSERT INTO top_channel VALUES ('SOS kanal', '727');
INSERT INTO top_channel VALUES ('Ona TV HD', '718');
INSERT INTO top_channel VALUES ('Agro TV', '691');
INSERT INTO top_channel VALUES ('TOK TV HD', '672');
INSERT INTO top_channel VALUES ('Pink Horror', '656');
INSERT INTO top_channel VALUES ('History2', '650');
INSERT INTO top_channel VALUES ('HAYAT HD', '649');
INSERT INTO top_channel VALUES ('FightBox', '648');
INSERT INTO top_channel VALUES ('FilmBox Premium', '645');
INSERT INTO top_channel VALUES ('RTV Zenica HD', '633');
INSERT INTO top_channel VALUES ('OBN', '625');
INSERT INTO top_channel VALUES ('Liverpul FC TV HD', '619');
INSERT INTO top_channel VALUES ('Prva Kick', '593');
INSERT INTO top_channel VALUES ('BIR TV HD', '590');
INSERT INTO top_channel VALUES ('RTV Puls Brčko distrikt BiH HD', '585');
INSERT INTO top_channel VALUES ('Arena Adrenalin HD', '569');
INSERT INTO top_channel VALUES ('BHT SD', '563');
INSERT INTO top_channel VALUES ('Dexy TV HD', '556');
INSERT INTO top_channel VALUES ('Cartoon Network', '551');
INSERT INTO top_channel VALUES ('Televizija M', '543');
INSERT INTO top_channel VALUES ('Prva Life', '539');
INSERT INTO top_channel VALUES ('TV Rudo HD', '534');
INSERT INTO top_channel VALUES ('Viasat Nature HD', '532');
INSERT INTO top_channel VALUES ('24Kitchen', '530');
INSERT INTO top_channel VALUES ('Adult 4', '519');
INSERT INTO top_channel VALUES ('FACE TV HD', '512');
INSERT INTO top_channel VALUES ('RTS Klasika', '510');
INSERT INTO top_channel VALUES ('RTS Kolo', '499');
INSERT INTO top_channel VALUES ('Prva Files', '497');
INSERT INTO top_channel VALUES ('Pink Pedia', '493');
INSERT INTO top_channel VALUES (' Kazbuka', '489');
INSERT INTO top_channel VALUES ('O Kanal Plus HD', '487');
INSERT INTO top_channel VALUES ('HGTV', '479');
INSERT INTO top_channel VALUES ('Fight Network', '478');
INSERT INTO top_channel VALUES ('BIG radio II program', '461');
INSERT INTO top_channel VALUES ('TV Simić HD', '460');
INSERT INTO top_channel VALUES ('Bang U', '459');
INSERT INTO top_channel VALUES ('Reality Kings TV', '453');
INSERT INTO top_channel VALUES ('Adult 3', '447');
INSERT INTO top_channel VALUES ('TV D+', '435');
INSERT INTO top_channel VALUES ('Arena Adrenalin', '433');
INSERT INTO top_channel VALUES ('RTV USK HD', '423');
INSERT INTO top_channel VALUES ('DM SAT', '421');
INSERT INTO top_channel VALUES ('Brazzers TV', '417');
INSERT INTO top_channel VALUES ('TV Alfa', '414');
INSERT INTO top_channel VALUES ('FilmBox Arthouse', '409');
INSERT INTO top_channel VALUES ('Euronews HD ', '407');
INSERT INTO top_channel VALUES ('Adult 1', '403');
INSERT INTO top_channel VALUES ('Hustler TV', '402');
INSERT INTO top_channel VALUES ('Current Time TV HD', '398');
INSERT INTO top_channel VALUES ('Pink Kids', '388');
INSERT INTO top_channel VALUES ('Private TV', '383');
INSERT INTO top_channel VALUES ('HAYAT 2 HD', '377');
INSERT INTO top_channel VALUES ('Pink Zabava', '370');
INSERT INTO top_channel VALUES ('Adult 2', '364');
INSERT INTO top_channel VALUES ('Arena Esport HD', '361');
INSERT INTO top_channel VALUES ('Disney Channel', '360');
INSERT INTO top_channel VALUES ('Babes', '354');
INSERT INTO top_channel VALUES ('Crime & Investigation', '340');
INSERT INTO top_channel VALUES ('Pink M', '336');
INSERT INTO top_channel VALUES ('Naxi radio', '334');
INSERT INTO top_channel VALUES ('RTL Living', '334');
INSERT INTO top_channel VALUES ('Disney Junior', '330');
INSERT INTO top_channel VALUES ('Pink Folk 2', '329');
INSERT INTO top_channel VALUES ('Kuvo TV HD', '321');
INSERT INTO top_channel VALUES ('Blue Hustler', '319');
INSERT INTO top_channel VALUES ('Fast&FunBox', '317');
INSERT INTO top_channel VALUES ('Pink Kuvar', '306');
INSERT INTO top_channel VALUES ('Pink Super Kids', '301');
INSERT INTO top_channel VALUES ('RTS Poletarac', '288');
INSERT INTO top_channel VALUES ('BN BIH HD', '268');
INSERT INTO top_channel VALUES ('Turizam TV', '267');
INSERT INTO top_channel VALUES ('Elita live 1', '267');
INSERT INTO top_channel VALUES ('HBO', '262');
INSERT INTO top_channel VALUES ('RTS 1 HD', '245');
INSERT INTO top_channel VALUES ('O KANAL HD', '242');
INSERT INTO top_channel VALUES ('RT Documentary HD', '240');
INSERT INTO top_channel VALUES ('Tropik TV HD', '239');
INSERT INTO top_channel VALUES ('DocuBox', '232');
INSERT INTO top_channel VALUES ('JimJam', '224');
INSERT INTO top_channel VALUES ('Hayat Stil i Život HD', '223');
INSERT INTO top_channel VALUES ('HBO 2', '223');
INSERT INTO top_channel VALUES ('Pink Music', '222');
INSERT INTO top_channel VALUES ('Pink Show', '221');
INSERT INTO top_channel VALUES ('Informer TV HD ', '219');
INSERT INTO top_channel VALUES ('HBO 3', '219');
INSERT INTO top_channel VALUES ('Bravo Music', '204');
INSERT INTO top_channel VALUES ('Pink World', '200');
INSERT INTO top_channel VALUES ('K::CN 2', '196');
INSERT INTO top_channel VALUES ('Nes radio', '195');
INSERT INTO top_channel VALUES ('LOL', '194');
INSERT INTO top_channel VALUES ('Cinemax', '189');
INSERT INTO top_channel VALUES ('HBO HD', '183');
INSERT INTO top_channel VALUES ('E! HD', '178');
INSERT INTO top_channel VALUES ('Alternativna TV HD', '177');
INSERT INTO top_channel VALUES ('Elita live 2', '171');
INSERT INTO top_channel VALUES ('Russia 24', '171');
INSERT INTO top_channel VALUES ('Elita live 3', '169');
INSERT INTO top_channel VALUES ('WILD', '168');
INSERT INTO top_channel VALUES ('Hayatovci', '168');
INSERT INTO top_channel VALUES ('Fashion TV', '167');
INSERT INTO top_channel VALUES ('Pink Style', '163');
INSERT INTO top_channel VALUES ('Pink Folk', '157');
INSERT INTO top_channel VALUES ('K::CN 3', '157');
INSERT INTO top_channel VALUES ('Elita live 4', '156');
INSERT INTO top_channel VALUES ('Amari', '153');
INSERT INTO top_channel VALUES ('Radio Kozara', '152');
INSERT INTO top_channel VALUES ('RTV TK', '152');
INSERT INTO top_channel VALUES ('DIVA', '151');
INSERT INTO top_channel VALUES ('HBO 2 HD', '149');
INSERT INTO top_channel VALUES ('City Play', '149');
INSERT INTO top_channel VALUES ('RTS Muzika', '148');
INSERT INTO top_channel VALUES ('Zelena TV Zdravlje', '147');
INSERT INTO top_channel VALUES ('RTV Vogosca HD', '147');
INSERT INTO top_channel VALUES ('Hayat Folk Box', '147');
INSERT INTO top_channel VALUES ('Naxi Rock radio', '147');
INSERT INTO top_channel VALUES ('Hayat LoveBox HD', '144');
INSERT INTO top_channel VALUES ('Kontakt radio', '144');
INSERT INTO top_channel VALUES ('Pink BH 1 ', '143');
INSERT INTO top_channel VALUES ('HBO 3 HD', '142');
INSERT INTO top_channel VALUES ('EG Melody', '140');
INSERT INTO top_channel VALUES ('Pink Music 2', '140');
INSERT INTO top_channel VALUES ('RTL Channel', '139');
INSERT INTO top_channel VALUES ('Da Vinci Learning HD', '138');
INSERT INTO top_channel VALUES ('RTR PLANETA', '135');
INSERT INTO top_channel VALUES ('Folk Melody', '135');
INSERT INTO top_channel VALUES ('MTV', '133');
INSERT INTO top_channel VALUES ('Radio BN', '131');
INSERT INTO top_channel VALUES ('NG Wild HD', '130');
INSERT INTO top_channel VALUES ('Kanal 6 HD', '129');
INSERT INTO top_channel VALUES ('OTV Valentino', '129');
INSERT INTO top_channel VALUES ('Naxi Kids radio', '128');
INSERT INTO top_channel VALUES ('Pink Reality', '127');
INSERT INTO top_channel VALUES ('Euronews BIH', '127');
INSERT INTO top_channel VALUES ('RED TV HD', '127');
INSERT INTO top_channel VALUES ('Cinemax HD', '126');
INSERT INTO top_channel VALUES ('RTS SVET HD', '126');
INSERT INTO top_channel VALUES ('Cinemax 2', '125');
INSERT INTO top_channel VALUES ('Televizija 5 HD', '125');
INSERT INTO top_channel VALUES ('CNN HD', '124');
INSERT INTO top_channel VALUES ('Pop Melody', '123');
INSERT INTO top_channel VALUES ('CGTN HD', '119');
INSERT INTO top_channel VALUES ('HA HA', '119');
INSERT INTO top_channel VALUES ('Pink & Roll', '118');
INSERT INTO top_channel VALUES ('Sky News', '117');
INSERT INTO top_channel VALUES ('MTV Igman', '117');
INSERT INTO top_channel VALUES ('Premier Liga HD', '114');
INSERT INTO top_channel VALUES ('EX YU Melody', '113');
INSERT INTO top_channel VALUES ('Pink Hits 2', '112');
INSERT INTO top_channel VALUES ('OTV Valentino HD', '109');
INSERT INTO top_channel VALUES ('Pink Hits ', '109');
INSERT INTO top_channel VALUES ('TV Zenica HD', '109');
INSERT INTO top_channel VALUES ('HiFi Music', '108');
INSERT INTO top_channel VALUES ('BVN', '108');
INSERT INTO top_channel VALUES ('O Kanal Music HD', '107');
INSERT INTO top_channel VALUES ('Pink Koncert', '101');
INSERT INTO top_channel VALUES ('TV 101', '101');
INSERT INTO top_channel VALUES ('Cinemax 2 HD', '100');
INSERT INTO top_channel VALUES ('RTV KD', '100');
INSERT INTO top_channel VALUES ('TV HB HD', '99');
INSERT INTO top_channel VALUES ('NarodnaTV HD', '98');
INSERT INTO top_channel VALUES ('Fox News Channel', '96');
INSERT INTO top_channel VALUES ('Pink Fashion', '95');
INSERT INTO top_channel VALUES ('Melos TV', '93');
INSERT INTO top_channel VALUES ('Hayat Music Box', '91');
INSERT INTO top_channel VALUES ('LH TV HD', '91');
INSERT INTO top_channel VALUES ('BIG radio I program', '90');
INSERT INTO top_channel VALUES ('Hits Melody', '88');
INSERT INTO top_channel VALUES ('K3', '88');
INSERT INTO top_channel VALUES ('Hayat Love Box HD', '88');
INSERT INTO top_channel VALUES ('TV Slon HD', '86');
INSERT INTO top_channel VALUES ('Radio RS', '84');
INSERT INTO top_channel VALUES ('SIM radio', '84');
INSERT INTO top_channel VALUES ('Rai 1 HD', '84');
INSERT INTO top_channel VALUES ('Cinema TV', '83');
INSERT INTO top_channel VALUES ('RTV 7 HD', '83');
INSERT INTO top_channel VALUES ('RTS 2 HD', '82');
INSERT INTO top_channel VALUES ('Gametoon', '79');
INSERT INTO top_channel VALUES ('Deutsche Welle', '78');
INSERT INTO top_channel VALUES ('Toxic Rap', '77');
INSERT INTO top_channel VALUES ('France 24', '77');
INSERT INTO top_channel VALUES ('Happy Reality 1', '76');
INSERT INTO top_channel VALUES ('Yachting TV HD', '74');
INSERT INTO top_channel VALUES ('Hustler TV HD', '72');
INSERT INTO top_channel VALUES ('AXN Spin', '71');
INSERT INTO top_channel VALUES ('Liverpool HD', '71');
INSERT INTO top_channel VALUES ('Hema TV', '70');
INSERT INTO top_channel VALUES ('RTS 3 HD', '68');
INSERT INTO top_channel VALUES ('Happy Reality 2', '66');
INSERT INTO top_channel VALUES ('Elita Live 1 HD', '66');
INSERT INTO top_channel VALUES ('Private TV HD', '64');
INSERT INTO top_channel VALUES ('RTV HB HD', '63');
INSERT INTO top_channel VALUES ('Al Jazeera English HD', '61');
INSERT INTO top_channel VALUES ('Arena Esports HD', '58');
INSERT INTO top_channel VALUES ('VESTI HD', '58');
INSERT INTO top_channel VALUES ('Brazzers TV SD', '57');
INSERT INTO top_channel VALUES ('Dorcel TV HD', '56');
INSERT INTO top_channel VALUES ('Bloomberg Adria ', '55');
INSERT INTO top_channel VALUES ('RTS Pletenica', '54');
INSERT INTO top_channel VALUES ('Radio Beograd 202', '53');
INSERT INTO top_channel VALUES ('Pink Extra', '52');
INSERT INTO top_channel VALUES ('Radio Beograd 1', '52');
INSERT INTO top_channel VALUES ('Rai 2 HD', '49');
INSERT INTO top_channel VALUES ('Radio Beograd 2', '49');
INSERT INTO top_channel VALUES ('Yachting TV', '49');
INSERT INTO top_channel VALUES ('Pink HD', '49');
INSERT INTO top_channel VALUES ('Pink Erotic 4', '48');
INSERT INTO top_channel VALUES ('Rai 3 HD', '47');
INSERT INTO top_channel VALUES ('FashionBox', '46');
INSERT INTO top_channel VALUES ('RTL', '45');
INSERT INTO top_channel VALUES ('Pink Erotic 7', '45');
INSERT INTO top_channel VALUES ('Pink Erotic 8', '43');
INSERT INTO top_channel VALUES ('Elita Live 2 HD', '43');
INSERT INTO top_channel VALUES ('RTS Rokenroler', '43');
INSERT INTO top_channel VALUES ('Pink Erotic 1', '42');
INSERT INTO top_channel VALUES ('Pink Erotic 5', '42');
INSERT INTO top_channel VALUES ('Pink Erotic 3', '42');
INSERT INTO top_channel VALUES ('TRT World HD', '42');
INSERT INTO top_channel VALUES ('Elita Live 4 HD', '40');
INSERT INTO top_channel VALUES ('ID HD', '40');
INSERT INTO top_channel VALUES ('Pink Erotic 2', '40');
INSERT INTO top_channel VALUES ('Pink Plus', '40');
INSERT INTO top_channel VALUES ('Rai News 24 HD', '39');
INSERT INTO top_channel VALUES ('RTS Džezer', '39');
INSERT INTO top_channel VALUES ('360TuneBox', '39');
INSERT INTO top_channel VALUES ('Elita Live 3 HD', '39');
INSERT INTO top_channel VALUES ('TVE', '38');
INSERT INTO top_channel VALUES ('Pink LOL', '37');
INSERT INTO top_channel VALUES ('Pink HA HA', '36');
INSERT INTO top_channel VALUES ('VOX', '35');
INSERT INTO top_channel VALUES ('Pink Erotic 6', '35');
INSERT INTO top_channel VALUES ('FOX News HD', '35');
INSERT INTO top_channel VALUES ('Toxic Folk  HD', '34');
INSERT INTO top_channel VALUES ('Kazbuka', '34');
INSERT INTO top_channel VALUES ('Tropik TV HD ', '33');
INSERT INTO top_channel VALUES ('RTL 2', '33');
INSERT INTO top_channel VALUES ('Toxic TV  HD', '31');
INSERT INTO top_channel VALUES ('RTS Džuboks', '29');
INSERT INTO top_channel VALUES ('Rai 1', '28');
INSERT INTO top_channel VALUES ('France 24 HD ', '28');
INSERT INTO top_channel VALUES ('HGTV HD', '27');
INSERT INTO top_channel VALUES ('Sky News Int', '27');
INSERT INTO top_channel VALUES ('RTS Vrteška', '26');
INSERT INTO top_channel VALUES ('Radio Beograd 3', '25');
INSERT INTO top_channel VALUES ('History 2 HD', '25');
INSERT INTO top_channel VALUES ('English Club TV', '24');
INSERT INTO top_channel VALUES ('Rai 3', '23');
INSERT INTO top_channel VALUES ('Playboy TV HD', '23');
INSERT INTO top_channel VALUES ('Fashion TV HD', '21');
INSERT INTO top_channel VALUES ('Rai News', '21');
INSERT INTO top_channel VALUES ('Rai 2', '20');
INSERT INTO top_channel VALUES ('Hayat Folk Box HD', '20');
INSERT INTO top_channel VALUES ('DW-TV HD', '19');
INSERT INTO top_channel VALUES ('Hayatovci HD', '19');
INSERT INTO top_channel VALUES ('PINK M', '19');
INSERT INTO top_channel VALUES ('History HD', '17');
INSERT INTO top_channel VALUES ('Current Time HD', '17');
INSERT INTO top_channel VALUES ('TVE HD', '15');
INSERT INTO top_channel VALUES ('MTV Europe', '15');
INSERT INTO top_channel VALUES ('O Kanal Plus', '15');
INSERT INTO top_channel VALUES ('HAYAT Music Box HD', '15');
INSERT INTO top_channel VALUES ('Logosoft info HD', '13');
INSERT INTO top_channel VALUES ('RTR Planeta', '13');
INSERT INTO top_channel VALUES ('Espreso TV', '12');
INSERT INTO top_channel VALUES ('Fight Network HD', '11');
INSERT INTO top_channel VALUES ('O Kanal Music', '11');
INSERT INTO top_channel VALUES ('Mosaic-Dokumentarni', '10');
INSERT INTO top_channel VALUES ('BRAVO Music', '10');
INSERT INTO top_channel VALUES ('Crime+ Investigation', '9');
INSERT INTO top_channel VALUES ('Filmbox Premium HD  ', '7');
INSERT INTO top_channel VALUES ('Eko vizija HD', '7');
INSERT INTO top_channel VALUES ('EroXXX HD', '6');
INSERT INTO top_channel VALUES ('Fight Box HD', '5');
INSERT INTO top_channel VALUES ('Sevdah TV HD', '5');
INSERT INTO top_channel VALUES ('TnT Kids HD', '5');
INSERT INTO top_channel VALUES ('DocuBox HD', '4');
INSERT INTO top_channel VALUES ('Gametoon HD ', '2');
INSERT INTO top_channel VALUES ('Fast&Fun Box HD', '1');
INSERT INTO top_channel VALUES ('Pink Folk 1', '1');
INSERT INTO top_channel VALUES ('TDC HD', '1');
INSERT INTO top_channel VALUES ('ArtHouse Filmbox', '1');
